version: "3.8"

services:
  api:
    container_name: api.dev
    image: fullstack.api.dev
    build: ./api
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    volumes: 
      - ./api/src:/api/src
    ports: 
      - 4000:4000

  ui:
    container_name: ui.dev
    image: fullstack.ui.dev
    build: ./ui
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    volumes: 
      - ./ui/src:/ui/src
    ports: 
      - 3000:3000
  
  # app:
  #   container_name: app-dev
  #   image: app-dev
  #   build:
  #     context: .
  #     target: development
  #   environment: 
  #     CHOKIDAR_USEPOLLING: "true"
  #   volumes:
  #     - ./src:/app/src
  #   ports:
  #     - 4000:3000
